name: ci

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'requirements.txt'
      - '.github/workflows/ci.yml'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

# Cancel older runs on the same ref
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install deps
        run: |
          python -m pip install --upgrade pip wheel
          pip install --prefer-binary -r requirements.txt

      - name: Run tests
        run: pytest -q --maxfail=1 -ra --junitxml=pytest.xml

      - name: Upload JUnit
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest.xml
          path: pytest.xml
          if-no-files-found: ignore




